-- ═══════════════════════════════════════════════════════════════════════════
-- 15_restore_alphabet_1_to_4.sql – Aufgaben für Stufen 1–4 wiederherstellen
-- Einmal ausführen, wenn die Alphabet-Items (1–4) fehlen (z.B. nach 09_seed_new_levels).
-- ═══════════════════════════════════════════════════════════════════════════

-- Stufe 1: Alphabet 1 (Alif–Khā)
UPDATE learning_levels SET description = 'Erste 7 Buchstaben des arabischen Alphabets (Alif, Bā, Tā, Thā, Dschīm, Ḥā, Khā) in allen 4 Schreibweisen (Anfangs-, Mittel-, End- und Einzelschreibweisen).' WHERE level_number = 1;
DELETE FROM learning_items WHERE level_id = 1;
INSERT INTO learning_items (level_id, content, transliteration, order_index, options)
SELECT 1, v.c, v.tr, v.ord, v.opts::jsonb FROM (VALUES
  (1, E'\u0623', 'Alif (Anfang & Allein)', '[{"id":"1","text":"Alif (Anfang & Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Alif (Mitte & Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Bā (Allein)","is_correct":false,"audio_url":null}]'),
  (2, E'\u0640\u0623', 'Alif (Mitte & Ende)', '[{"id":"1","text":"Alif (Mitte & Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Alif (Anfang & Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Bā (Ende)","is_correct":false,"audio_url":null}]'),
  (3, E'\u0628', 'Bā (Allein)', '[{"id":"1","text":"Bā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Tā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Alif (Mitte & Ende)","is_correct":false,"audio_url":null}]'),
  (4, E'\u0628\u0640', 'Bā (Anfang)', '[{"id":"1","text":"Bā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Bā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Tā (Anfang)","is_correct":false,"audio_url":null}]'),
  (5, E'\u0640\u0628', 'Bā (Ende)', '[{"id":"1","text":"Bā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Bā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Tā (Ende)","is_correct":false,"audio_url":null}]'),
  (6, E'\u062A', 'Tā (Allein)', '[{"id":"1","text":"Tā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Bā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Thā (Allein)","is_correct":false,"audio_url":null}]'),
  (7, E'\u062A\u0640', 'Tā (Anfang)', '[{"id":"1","text":"Tā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Tā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Thā (Anfang)","is_correct":false,"audio_url":null}]'),
  (8, E'\u0640\u062A', 'Tā (Ende)', '[{"id":"1","text":"Tā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Tā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Thā (Ende)","is_correct":false,"audio_url":null}]'),
  (9, E'\u062B', 'Thā (Allein)', '[{"id":"1","text":"Thā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Tā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Dschīm (Allein)","is_correct":false,"audio_url":null}]'),
  (10, E'\u062B\u0640', 'Thā (Anfang)', '[{"id":"1","text":"Thā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Thā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Dschīm (Anfang)","is_correct":false,"audio_url":null}]'),
  (11, E'\u0640\u062B', 'Thā (Ende)', '[{"id":"1","text":"Thā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Thā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Dschīm (Ende)","is_correct":false,"audio_url":null}]'),
  (12, E'\u062C', 'Dschīm (Allein)', '[{"id":"1","text":"Dschīm (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Thā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Ḥā (Allein)","is_correct":false,"audio_url":null}]'),
  (13, E'\u062C\u0640', 'Dschīm (Anfang)', '[{"id":"1","text":"Dschīm (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Dschīm (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Ḥā (Anfang)","is_correct":false,"audio_url":null}]'),
  (14, E'\u0640\u062C', 'Dschīm (Ende)', '[{"id":"1","text":"Dschīm (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Dschīm (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Khā (Ende)","is_correct":false,"audio_url":null}]'),
  (15, E'\u062D', 'Ḥā (Allein)', '[{"id":"1","text":"Ḥā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Dschīm (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Khā (Allein)","is_correct":false,"audio_url":null}]'),
  (16, E'\u062D\u0640', 'Ḥā (Anfang)', '[{"id":"1","text":"Ḥā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Ḥā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Khā (Anfang)","is_correct":false,"audio_url":null}]'),
  (17, E'\u0640\u062D', 'Ḥā (Ende)', '[{"id":"1","text":"Ḥā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Ḥā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Khā (Ende)","is_correct":false,"audio_url":null}]'),
  (18, E'\u062E', 'Khā (Allein)', '[{"id":"1","text":"Khā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Ḥā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Bā (Allein)","is_correct":false,"audio_url":null}]'),
  (19, E'\u062E\u0640', 'Khā (Anfang)', '[{"id":"1","text":"Khā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Khā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Bā (Anfang)","is_correct":false,"audio_url":null}]'),
  (20, E'\u0640\u062E', 'Khā (Ende)', '[{"id":"1","text":"Khā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Khā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ḥā (Ende)","is_correct":false,"audio_url":null}]')
) AS v(ord, c, tr, opts);

-- Stufe 2: Alphabet 2
UPDATE learning_levels SET description = 'Zweite 8 Buchstaben: Dāl, Dhāl, Rā, Zāy (je 2 Formen), Sīn, Shīn, Ṣād, Ḍād (Anfangs-, Mittel-, End- und Einzelform).' WHERE level_number = 2;
DELETE FROM learning_items WHERE level_id = 2;
INSERT INTO learning_items (level_id, content, transliteration, order_index, options)
SELECT 2, v.c, v.tr, v.ord, v.opts::jsonb FROM (VALUES
  (1, E'\u062F', 'Dāl (Allein & Anfang)', '[{"id":"1","text":"Dāl (Allein & Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Dāl (Mitte & Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Dhāl (Allein & Anfang)","is_correct":false,"audio_url":null}]'),
  (2, E'\u0640\u062F', 'Dāl (Mitte & Ende)', '[{"id":"1","text":"Dāl (Mitte & Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Dāl (Allein & Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Dhāl (Mitte & Ende)","is_correct":false,"audio_url":null}]'),
  (3, E'\u0630', 'Dhāl (Allein & Anfang)', '[{"id":"1","text":"Dhāl (Allein & Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Dhāl (Mitte & Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Rā (Allein & Anfang)","is_correct":false,"audio_url":null}]'),
  (4, E'\u0640\u0630', 'Dhāl (Mitte & Ende)', '[{"id":"1","text":"Dhāl (Mitte & Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Dhāl (Allein & Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Zāy (Mitte & Ende)","is_correct":false,"audio_url":null}]'),
  (5, E'\u0631', 'Rā (Allein & Anfang)', '[{"id":"1","text":"Rā (Allein & Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Rā (Mitte & Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Zāy (Allein & Anfang)","is_correct":false,"audio_url":null}]'),
  (6, E'\u0640\u0631', 'Rā (Mitte & Ende)', '[{"id":"1","text":"Rā (Mitte & Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Rā (Allein & Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Dāl (Mitte & Ende)","is_correct":false,"audio_url":null}]'),
  (7, E'\u0632', 'Zāy (Allein & Anfang)', '[{"id":"1","text":"Zāy (Allein & Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Zāy (Mitte & Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Sīn (Allein)","is_correct":false,"audio_url":null}]'),
  (8, E'\u0640\u0632', 'Zāy (Mitte & Ende)', '[{"id":"1","text":"Zāy (Mitte & Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Zāy (Allein & Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Rā (Mitte & Ende)","is_correct":false,"audio_url":null}]'),
  (9, E'\u0633', 'Sīn (Allein)', '[{"id":"1","text":"Sīn (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Shīn (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Ṣād (Allein)","is_correct":false,"audio_url":null}]'),
  (10, E'\u0633\u0640', 'Sīn (Anfang)', '[{"id":"1","text":"Sīn (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Sīn (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Shīn (Anfang)","is_correct":false,"audio_url":null}]'),
  (11, E'\u0640\u0633', 'Sīn (Ende)', '[{"id":"1","text":"Sīn (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Sīn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Shīn (Ende)","is_correct":false,"audio_url":null}]'),
  (12, E'\u0634', 'Shīn (Allein)', '[{"id":"1","text":"Shīn (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Sīn (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Ṣād (Allein)","is_correct":false,"audio_url":null}]'),
  (13, E'\u0634\u0640', 'Shīn (Anfang)', '[{"id":"1","text":"Shīn (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Shīn (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Ṣād (Anfang)","is_correct":false,"audio_url":null}]'),
  (14, E'\u0640\u0634', 'Shīn (Ende)', '[{"id":"1","text":"Shīn (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Shīn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ḍād (Ende)","is_correct":false,"audio_url":null}]'),
  (15, E'\u0635', 'Ṣād (Allein)', '[{"id":"1","text":"Ṣād (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Shīn (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Ḍād (Allein)","is_correct":false,"audio_url":null}]'),
  (16, E'\u0635\u0640', 'Ṣād (Anfang)', '[{"id":"1","text":"Ṣād (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Ṣād (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Ḍād (Anfang)","is_correct":false,"audio_url":null}]'),
  (17, E'\u0640\u0635', 'Ṣād (Ende)', '[{"id":"1","text":"Ṣād (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Ṣād (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ḍād (Ende)","is_correct":false,"audio_url":null}]'),
  (18, E'\u0636', 'Ḍād (Allein)', '[{"id":"1","text":"Ḍād (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Ṣād (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Sīn (Allein)","is_correct":false,"audio_url":null}]'),
  (19, E'\u0636\u0640', 'Ḍād (Anfang)', '[{"id":"1","text":"Ḍād (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Ḍād (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Ṣād (Anfang)","is_correct":false,"audio_url":null}]'),
  (20, E'\u0640\u0636', 'Ḍād (Ende)', '[{"id":"1","text":"Ḍād (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Ḍād (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ṣād (Ende)","is_correct":false,"audio_url":null}]')
) AS v(ord, c, tr, opts);

-- Stufe 3: Alphabet 3
UPDATE learning_levels SET description = 'Dritte 7 Buchstaben: Ṭā, Ẓā, ʿAyn, Ghayn, Fā, Qāf, Kāf – je 4 Formen (Allein, Anfang, Mitte, Ende).' WHERE level_number = 3;
DELETE FROM learning_items WHERE level_id = 3;
INSERT INTO learning_items (level_id, content, transliteration, order_index, options)
SELECT 3, v.c, v.tr, v.ord, v.opts::jsonb FROM (VALUES
  (1, E'\u0637', 'Ṭā (Allein)', '[{"id":"1","text":"Ṭā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Ẓā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"ʿAyn (Allein)","is_correct":false,"audio_url":null}]'),
  (2, E'\u0637\u0640', 'Ṭā (Anfang)', '[{"id":"1","text":"Ṭā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Ṭā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Ẓā (Anfang)","is_correct":false,"audio_url":null}]'),
  (3, E'\u0640\u0637\u0640', 'Ṭā (Mitte)', '[{"id":"1","text":"Ṭā (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Ṭā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ẓā (Mitte)","is_correct":false,"audio_url":null}]'),
  (4, E'\u0640\u0637', 'Ṭā (Ende)', '[{"id":"1","text":"Ṭā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Ṭā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ẓā (Ende)","is_correct":false,"audio_url":null}]'),
  (5, E'\u0638', 'Ẓā (Allein)', '[{"id":"1","text":"Ẓā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Ṭā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"ʿAyn (Allein)","is_correct":false,"audio_url":null}]'),
  (6, E'\u0638\u0640', 'Ẓā (Anfang)', '[{"id":"1","text":"Ẓā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Ẓā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Ṭā (Anfang)","is_correct":false,"audio_url":null}]'),
  (7, E'\u0640\u0638\u0640', 'Ẓā (Mitte)', '[{"id":"1","text":"Ẓā (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Ẓā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"ʿAyn (Mitte)","is_correct":false,"audio_url":null}]'),
  (8, E'\u0640\u0638', 'Ẓā (Ende)', '[{"id":"1","text":"Ẓā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Ẓā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ṭā (Ende)","is_correct":false,"audio_url":null}]'),
  (9, E'\u0639', 'ʿAyn (Allein)', '[{"id":"1","text":"ʿAyn (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Ghayn (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Ẓā (Allein)","is_correct":false,"audio_url":null}]'),
  (10, E'\u0639\u0640', 'ʿAyn (Anfang)', '[{"id":"1","text":"ʿAyn (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"ʿAyn (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Ghayn (Anfang)","is_correct":false,"audio_url":null}]'),
  (11, E'\u0640\u0639\u0640', 'ʿAyn (Mitte)', '[{"id":"1","text":"ʿAyn (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"ʿAyn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ghayn (Mitte)","is_correct":false,"audio_url":null}]'),
  (12, E'\u0640\u0639', 'ʿAyn (Ende)', '[{"id":"1","text":"ʿAyn (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"ʿAyn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Ghayn (Ende)","is_correct":false,"audio_url":null}]'),
  (13, E'\u063A', 'Ghayn (Allein)', '[{"id":"1","text":"Ghayn (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"ʿAyn (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Fā (Allein)","is_correct":false,"audio_url":null}]'),
  (14, E'\u063A\u0640', 'Ghayn (Anfang)', '[{"id":"1","text":"Ghayn (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Ghayn (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"ʿAyn (Anfang)","is_correct":false,"audio_url":null}]'),
  (15, E'\u0640\u063A\u0640', 'Ghayn (Mitte)', '[{"id":"1","text":"Ghayn (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Ghayn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Fā (Mitte)","is_correct":false,"audio_url":null}]'),
  (16, E'\u0640\u063A', 'Ghayn (Ende)', '[{"id":"1","text":"Ghayn (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Ghayn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"ʿAyn (Ende)","is_correct":false,"audio_url":null}]'),
  (17, E'\u0641', 'Fā (Allein)', '[{"id":"1","text":"Fā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Qāf (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Ghayn (Allein)","is_correct":false,"audio_url":null}]'),
  (18, E'\u0641\u0640', 'Fā (Anfang)', '[{"id":"1","text":"Fā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Fā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Qāf (Anfang)","is_correct":false,"audio_url":null}]'),
  (19, E'\u0640\u0641\u0640', 'Fā (Mitte)', '[{"id":"1","text":"Fā (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Fā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Qāf (Mitte)","is_correct":false,"audio_url":null}]'),
  (20, E'\u0640\u0641', 'Fā (Ende)', '[{"id":"1","text":"Fā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Fā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Qāf (Ende)","is_correct":false,"audio_url":null}]'),
  (21, E'\u0642', 'Qāf (Allein)', '[{"id":"1","text":"Qāf (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Fā (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Kāf (Allein)","is_correct":false,"audio_url":null}]'),
  (22, E'\u0642\u0640', 'Qāf (Anfang)', '[{"id":"1","text":"Qāf (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Qāf (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Kāf (Anfang)","is_correct":false,"audio_url":null}]'),
  (23, E'\u0640\u0642\u0640', 'Qāf (Mitte)', '[{"id":"1","text":"Qāf (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Qāf (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Kāf (Mitte)","is_correct":false,"audio_url":null}]'),
  (24, E'\u0640\u0642', 'Qāf (Ende)', '[{"id":"1","text":"Qāf (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Qāf (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Fā (Ende)","is_correct":false,"audio_url":null}]'),
  (25, E'\u0643', 'Kāf (Allein)', '[{"id":"1","text":"Kāf (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Qāf (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Fā (Allein)","is_correct":false,"audio_url":null}]'),
  (26, E'\u0643\u0640', 'Kāf (Anfang)', '[{"id":"1","text":"Kāf (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Kāf (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Qāf (Anfang)","is_correct":false,"audio_url":null}]'),
  (27, E'\u0640\u0643\u0640', 'Kāf (Mitte)', '[{"id":"1","text":"Kāf (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Kāf (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Qāf (Mitte)","is_correct":false,"audio_url":null}]'),
  (28, E'\u0640\u0643', 'Kāf (Ende)', '[{"id":"1","text":"Kāf (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Kāf (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Qāf (Ende)","is_correct":false,"audio_url":null}]')
) AS v(ord, c, tr, opts);

-- Stufe 4: Alphabet 4
UPDATE learning_levels SET description = 'Vierte 6 Buchstaben: Lām, Mīm, Nūn, Hā (je 4 Formen), Wāw (2 Formen), Yā (4 Formen).' WHERE level_number = 4;
DELETE FROM learning_items WHERE level_id = 4;
INSERT INTO learning_items (level_id, content, transliteration, order_index, options)
SELECT 4, v.c, v.tr, v.ord, v.opts::jsonb FROM (VALUES
  (1, E'\u0644', 'Lām (Allein)', '[{"id":"1","text":"Lām (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Mīm (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Nūn (Allein)","is_correct":false,"audio_url":null}]'),
  (2, E'\u0644\u0640', 'Lām (Anfang)', '[{"id":"1","text":"Lām (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Lām (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Mīm (Anfang)","is_correct":false,"audio_url":null}]'),
  (3, E'\u0640\u0644\u0640', 'Lām (Mitte)', '[{"id":"1","text":"Lām (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Lām (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Nūn (Mitte)","is_correct":false,"audio_url":null}]'),
  (4, E'\u0640\u0644', 'Lām (Ende)', '[{"id":"1","text":"Lām (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Lām (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Yā (Ende)","is_correct":false,"audio_url":null}]'),
  (5, E'\u0645', 'Mīm (Allein)', '[{"id":"1","text":"Mīm (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Lām (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Nūn (Allein)","is_correct":false,"audio_url":null}]'),
  (6, E'\u0645\u0640', 'Mīm (Anfang)', '[{"id":"1","text":"Mīm (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Mīm (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Nūn (Anfang)","is_correct":false,"audio_url":null}]'),
  (7, E'\u0640\u0645\u0640', 'Mīm (Mitte)', '[{"id":"1","text":"Mīm (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Mīm (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Hā (Mitte)","is_correct":false,"audio_url":null}]'),
  (8, E'\u0640\u0645', 'Mīm (Ende)', '[{"id":"1","text":"Mīm (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Mīm (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Nūn (Ende)","is_correct":false,"audio_url":null}]'),
  (9, E'\u0646', 'Nūn (Allein)', '[{"id":"1","text":"Nūn (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Mīm (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Hā (Allein)","is_correct":false,"audio_url":null}]'),
  (10, E'\u0646\u0640', 'Nūn (Anfang)', '[{"id":"1","text":"Nūn (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Nūn (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Hā (Anfang)","is_correct":false,"audio_url":null}]'),
  (11, E'\u0640\u0646\u0640', 'Nūn (Mitte)', '[{"id":"1","text":"Nūn (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Nūn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Yā (Mitte)","is_correct":false,"audio_url":null}]'),
  (12, E'\u0640\u0646', 'Nūn (Ende)', '[{"id":"1","text":"Nūn (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Nūn (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Mīm (Ende)","is_correct":false,"audio_url":null}]'),
  (13, E'\u0647', 'Hā (Allein)', '[{"id":"1","text":"Hā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Nūn (Allein)","is_correct":false,"audio_url":null},{"id":"3","text":"Wāw (Allein & Anfang)","is_correct":false,"audio_url":null}]'),
  (14, E'\u0647\u0640', 'Hā (Anfang)', '[{"id":"1","text":"Hā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Hā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Yā (Anfang)","is_correct":false,"audio_url":null}]'),
  (15, E'\u0640\u0647\u0640', 'Hā (Mitte)', '[{"id":"1","text":"Hā (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Hā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Nūn (Mitte)","is_correct":false,"audio_url":null}]'),
  (16, E'\u0640\u0647', 'Hā (Ende)', '[{"id":"1","text":"Hā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Hā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Yā (Ende)","is_correct":false,"audio_url":null}]'),
  (17, E'\u0648', 'Wāw (Allein & Anfang)', '[{"id":"1","text":"Wāw (Allein & Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Wāw (Mitte & Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Yā (Allein)","is_correct":false,"audio_url":null}]'),
  (18, E'\u0640\u0648', 'Wāw (Mitte & Ende)', '[{"id":"1","text":"Wāw (Mitte & Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Wāw (Allein & Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Hā (Ende)","is_correct":false,"audio_url":null}]'),
  (19, E'\u064A', 'Yā (Allein)', '[{"id":"1","text":"Yā (Allein)","is_correct":true,"audio_url":null},{"id":"2","text":"Wāw (Allein & Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Hā (Allein)","is_correct":false,"audio_url":null}]'),
  (20, E'\u064A\u0640', 'Yā (Anfang)', '[{"id":"1","text":"Yā (Anfang)","is_correct":true,"audio_url":null},{"id":"2","text":"Yā (Ende)","is_correct":false,"audio_url":null},{"id":"3","text":"Lām (Anfang)","is_correct":false,"audio_url":null}]'),
  (21, E'\u0640\u064A\u0640', 'Yā (Mitte)', '[{"id":"1","text":"Yā (Mitte)","is_correct":true,"audio_url":null},{"id":"2","text":"Yā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Nūn (Mitte)","is_correct":false,"audio_url":null}]'),
  (22, E'\u0640\u064A', 'Yā (Ende)', '[{"id":"1","text":"Yā (Ende)","is_correct":true,"audio_url":null},{"id":"2","text":"Yā (Anfang)","is_correct":false,"audio_url":null},{"id":"3","text":"Lām (Ende)","is_correct":false,"audio_url":null}]')
) AS v(ord, c, tr, opts);
